# Generated by Django 4.2.2 on 2023-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнение'),
        ),
    ]
